import Aura from '@primeuix/themes/aura'

export const primeVueConfig = {
  theme: {
    preset: Aura
  },
  locale: {
    accept: 'Tak',
    reject: 'Nie',
    choose: 'Wybierz',
    upload: 'Prześlij',
    cancel: 'Anuluj',
    dayNames: ['Niedziela', 'Poniedziałek', 'Wtorek', 'Środa', 'Czwartek', 'Piątek', 'Sobota'],
    dayNamesShort: ['Ndz', 'Pon', 'Wt', 'Śr', 'Czw', 'Pt', 'Sob'],
    dayNamesMin: ['N', 'P', 'W', 'Ś', 'C', 'P', 'S'],
    monthNames: ['Styczeń', 'Luty', 'Marzec', 'Kwiecień', 'Maj', 'Czerwiec', 'Lipiec', 'Sierpień', 'Wrzesień', 'Październik', 'Listopad', 'Grudzień'],
    monthNamesShort: ['Sty', 'Lut', 'Mar', 'Kwi', 'Maj', 'Cze', 'Lip', 'Sie', 'Wrz', 'Paź', 'Lis', 'Gru'],
    today: 'Dzisiaj',
    clear: 'Wyczyść',
    weekHeader: 'Tydz',
    firstDayOfWeek: 1,
    dateFormat: 'dd.mm.yy',
    weak: 'Słabe',
    medium: 'Średnie',
    strong: 'Silne',
    passwordPrompt: 'Wprowadź hasło',
    emptyMessage: 'Brak wyników',
    emptyFilterMessage: 'Brak wyników',
    searchMessage: 'Dostępnych jest {0} wyników',
    selectionMessage: 'Wybrano {0} elementów',
    emptySelectionMessage: 'Nie wybrano żadnego elementu',
    emptySearchMessage: 'Brak wyników',
    fileSizeTypes: ['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'],
    aria: {
      trueLabel: 'Prawda',
      falseLabel: 'Fałsz',
      nullLabel: 'Nie wybrano',
      star: '1 gwiazdka',
      stars: '{star} gwiazdek',
      selectAll: 'Zaznacz wszystko',
      unselectAll: 'Odznacz wszystko',
      close: 'Zamknij',
      previous: 'Poprzedni',
      next: 'Następny',
      navigation: 'Nawigacja',
      scrollTop: 'Przewiń do góry',
      moveTop: 'Przenieś na górę',
      moveUp: 'Przenieś w górę',
      moveDown: 'Przenieś w dół',
      moveBottom: 'Przenieś na dół',
      moveToTarget: 'Przenieś do celu',
      moveToSource: 'Przenieś do źródła',
      moveAllToTarget: 'Przenieś wszystko do celu',
      moveAllToSource: 'Przenieś wszystko do źródła',
      pageLabel: 'Strona {page}',
      firstPageLabel: 'Pierwsza strona',
      lastPageLabel: 'Ostatnia strona',
      nextPageLabel: 'Następna strona',
      previousPageLabel: 'Poprzednia strona',
      rowsPerPageLabel: 'Wierszy na stronę',
      jumpToPageDropdownLabel: 'Przejdź do strony',
      jumpToPageInputLabel: 'Przejdź do strony',
      selectRow: 'Wybrano wiersz',
      unselectRow: 'Odznaczono wiersz',
      expandRow: 'Rozwiń wiersz',
      collapseRow: 'Zwiń wiersz',
      showFilterMenu: 'Pokaż filtr',
      hideFilterMenu: 'Ukryj filtr',
      filterOperator: 'Operator filtra',
      filterConstraint: 'Ograniczenie filtra',
      editRow: 'Edytuj wiersz',
      saveEdit: 'Zapisz',
      cancelEdit: 'Anuluj',
      listView: 'Widok listy',
      gridView: 'Widok siatki',
      slide: 'Slajd',
      slideNumber: '{slideNumber}',
      zoomImage: 'Powiększ obraz',
      zoomIn: 'Powiększ',
      zoomOut: 'Pomniejsz',
      rotateRight: 'Obróć w prawo',
      rotateLeft: 'Obróć w lewo'
    }
  }
}
